apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-nginx-service
spec:
  rules:
    - host: pfe.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-nginx-service
                port:
                  number: 80
