apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-nginx
  template:
    metadata:
      labels:
        app: frontend-nginx
    spec:
      containers:
        - name: nginx
          image: yassinehwass/front-izi
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-nginx-service
spec:
  selector:
    app: frontend-nginx
  ports:
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
