# Use the official MySQL Docker image as the base
FROM mysql:5.7

# Set environment variables for the MySQL database
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=employee_management_system
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=root

EXPOSE 3306

CMD ["mysqld"]
