version: '3'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    deploy:
      mode: replicated
      replicas: 1

